name: Deploy wine-app-backend
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t tranvix0910/wine_app_backend  .
      - name: Publish Image to docker hub
        run: docker push tranvix0910/wine_app_backend:latest
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull tranvix0910/wine_app_backend:latest
      - name: Delete old container
        run: docker rm -f wine_app_backend-container
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name wine_app_backend-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' tranvix0910/wine_app_backend